### ISSUE TITLE
Built addLargeScaleCharacteristics

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/LargeScaleCharacteristics#14]
name of the columns should be {table_name}_{concept_id}_{window_name} and 1 / 0 regarding the presence or absence of that code

**Comment by MimiYuchenGuo** [comment]
do we allow multiple target cohort ids (vector) for this function as well?

**Comment by catalamarti** [comment]
nope, it works with the x table. It is like CohortProfiles
