### ISSUE TITLE
LargeScaleCharacterization for source codes

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/LargeScaleCharacteristics#19]
Hi @ajoedicke @albertpratsu @edward-burn,

To put context, LargeScaleCharacterization: the name of the package is prety clear of what it does hahaha.

I have some questions for users,
In each table (e.g. condition_occurrence) we have two concept columns: one refers to the standard code, the mapped one (e.g. condition_concept_id), and the other refers to the original source data (e.g. condition_source_concept_id). When a code is not mapped it appears as concept_id = 0 and we have to check source_concept_id to see which is the original code. This situation causes that usually concept_id = 0 is one of the most common codes in LSC. That's why currently we are not reporting concept_id = 0.

Here the first question:
1) Should we report the counts of concept_id = 0?

For the large scale characterization we are going to add an argument to also characterize the non standard codes (source_concept_id). Currently we are only characterizing the standard ones. Then the question is:
2) Should we characterize source_concept_id for all cases or only for concept_id = 0?

Note that source_concept_id can also be zero. If we report all source_concept_id, I would assume that answer to Question 1 will apply to this case too. 
3) Is that okay?

**Comment by edward-burn** [comment]
@catalamarti for me I would exclude concept I'd of 0 (either in the standard or source) from the characterisation. 

Curious the rationale for large scale characterisation of source codes? Not to say not to do it, just wondering about the use case for it?

**Comment by catalamarti** [comment]
@edward-burn  I don't know, if it is going to be useful or not, probably this is a question also for users.
I would say that characterizing the concept_id = 0 would be interesting. But not so sure to characterize everthing.

**Comment by catalamarti** [comment]
no (for the moment)
