### ISSUE TITLE
Change result format

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/LargeScaleCharacteristics#2]
The output will be a unique tibble (not a list like now): with the following columns: cohort_definition_id, table_id, table_name, window_id, window_name, concept_id, concept_name, concept_type, concept_count, denominator_count

concept_type will be "Standard", "Non-standard", or "Classification" for the moment all will be "Standard"

**Comment by MimiYuchenGuo** [comment]
@catalamarti Do we still want the obscure counts?

**Comment by catalamarti** [comment]
When obscured we will change denominator _count and/or numerator_count to <5
