### ISSUE TITLE
change output format of getLSC

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/LargeScaleCharacteristics#26]
only export the following columns: cohort_name, table_name, window_name, concept_id, concept_name, concept_count, denominator_count, overlap, concept_type, cdm_name

cdm_name is obtained from: CDMConnector::cdmName(cdm)
cohort_name is obtained from: CDMConnector::cohortSet(cdm$cohort) this will give you a tibble with cohort_definition_id and cohort_name

**Comment by MimiYuchenGuo** [comment]
getLSC function takes targetCohortName as input, why would we need cohort_name again?
