### ISSUE TITLE
Built getDescendantCounts(x, cdm)

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/LargeScaleCharacteristics#35]
x is a sql table that at least has five columns: "cohort_name", "table_name", "window_name", "concept_id", "concept_count"
No need to check as it is an internal function
inner_join with cdm$concept_ancestor (descendat_concept_id = concept_id) and group_by(cohort_name, table_name, window_name, ancestor_concept_id) %>% summarise(concept_count = sum(concept_count))
rename: ancestor_concept_id = concept_id
The resultant table will contain the same format that the input one but with different content

**Comment by MimiYuchenGuo** [comment]
@catalamarti do we allow user to provide an ancestor dataframe like codelist generator? or just refer to cdm$concept_ancestor?

https://github.com/darwin-eu/CodelistGenerator/blob/990a669fa8611011aab6274f4465084925c13ec2/R/runSearch.R#L767

**Comment by edward-burn** [comment]
@MimiYuchenGuo I think better for you (without having seen the code) that you do this on the database side

**Comment by MimiYuchenGuo** [comment]
so if includeDescendants == TRUE. only return descendants counts not concept counts? or both?
