### ISSUE TITLE
Check that cdm$condition_occurrence has condition_end_date

### ISSUE THREAD

**Issue by KimLopezGuell** [oxford-pharmacoepi/LargeScaleCharacteristics#39]
I noticed while working with other ddbb that some have condition_end_date = NA, and the function was outputting empty tables. You could check that and do condition_end_date = condition_start_date in that case, the function then works fine.

**Comment by KimLopezGuell** [comment]
@catalamarti @MimiYuchenGuo

**Comment by catalamarti** [comment]
so my point would be to add something like this:
```
condition_occurrence <- cdm$condition_occurrence %>%
  dplyr::mutate(condition_end_date = dplyr::if_else(is.na(.data$condition_end_date), .data$condition_start_date, .data$condition_end_date))
```
But is in the scope of this package?
@edward-burn @KimLopezGuell @MimiYuchenGuo 

If we do that we should apply to other tables too
